select
  cast(as_of_date as date) as as_of_date,
  customer_id,
  customer_name,
  email,
  upper(trim(segment)) as segment,
  upper(trim(region)) as region,
  product_tier,
  contract_type,
  payment_method,
  case when lower(has_autopay) in ('true','1','yes','y') then true else false end as has_autopay,
  {{ safe_cast('tenure_months', 'int') }} as tenure_months,
  {{ safe_cast('monthly_charges', 'decimal(10,2)') }} as monthly_charges,
  {{ safe_cast('total_charges', 'decimal(12,2)') }} as total_charges,
  {{ safe_cast('num_logins_30d', 'bigint') }} as num_logins_30d,
  {{ safe_cast('support_tickets_90d', 'bigint') }} as support_tickets_90d,
  {{ safe_cast('last_login_days_ago', 'int') }} as last_login_days_ago,
  {{ safe_cast('nps_score', 'int') }} as nps_score,
  {{ safe_cast('csat_score', 'decimal(5,2)') }} as csat_score,
  {{ safe_cast('is_active', 'boolean') }} as is_active,
  {{ safe_cast('churn_next_30d', 'boolean') }} as churn_next_30d
from {{ source('churn_bronze','churn_raw') }}